#!/bin/sh
cd `dirname $0`/..
wk_dir=`pwd`
script_dir=${wk_dir}/script
cd ${script_dir}
script_name=`basename $0`
job_name="`basename $0 .sh`"
script_path=${script_dir}/${script_name}
bin_dir=${wk_dir}/bin
conf_dir=${wk_dir}/conf
util_dir=${wk_dir}/util
jar_dir=${wk_dir}/jar
alert_dir=${wk_dir}/alert
flag_dir=${wk_dir}/flag
log_dir=${wk_dir}/log/crontab
ktrs_dir=${wk_dir}/ktrs

if [ ! -d "${log_dir}" ]; then
  mkdir -p ${log_dir}
fi

d0=`date +'%Y%m%d'`
d1=`date +'%Y%m%d' -d -1day`
d7=`date +'%Y%m%d' -d -7day`

if [ $# -ge 1 ]; then
  d1=`date +'%Y%m%d' -d $1`
  d7=`date +'%Y%m%d' -d "$1 -6day"`
fi

# config ############################
source ${conf_dir}/default.conf
source ${conf_dir}/vars.conf
source ${conf_dir}/alert.conf

# utils #############################
source ${util_dir}/static_hive_lib
source ${alert_dir}/alert
source ${util_dir}/static_functions

