#!/bin/bash
# desc : my commonly used functions

function current_ts() {
  now=`date "+%Y%m%d_%H%M%S"`
  echo $now
}

function current() {
  now=`date "+%Y-%m-%d %H:%M:%S"`
  echo $now
}

function echo_ex() {
  now=`current`
  echo "${now} $1"
}

check_hive_plat_and_dt_partitions() {
  table_name="$1"
  plat="$2"
  dt="$3"
  check_hive_partitions ${table_name} platform=${plat}/dt=${d1} || return 255
  return 0
}

function check_success() {
  if [ $? -ne 0 ] ; then
    alert "$job_name" "failure-$d1" "${log_uri}"
    echo_ex "Last shell Sentence or jobTask run failed! so, exit 255"
    exit 255
  fi
  echo_ex "Last shell sentence or jobTask run successful!"
}

function is_sunday() {
  what_day=`date -d $1 +%A`
  echo "what_day : " $what_day
  tar_day01="Sunday"
  tar_day02="星期日"
  if [[ ${what_day} == ${tar_day01} ]] || [[ ${what_day} == ${tar_day02} ]]; then
    return 0
  fi
  return 255
}

