#!/bin/bash
source ${conf_dir}/alert.conf
function alert() {
  local script_name=$1
  local status_dt=$2
  local content=$3
  python ${alert_dir}/send_mail.py 数据组\ :\ ${module_name}-${script_name}\ ${status_dt} $content $mailto
}
#function alert_msg() {
#  if [ $? -ne 0 ] ; then
#    alert "$job_name" "failure-$d1" "${log_uri}"
#    exit 255
#  fi
#}
